name: CI/CD - build and deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run tests
        run: go test ./...

      - name: Build binary
        run: GOOS=linux GOARCH=amd64 go build -o mathapp .

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts || true

          # Copy binary to EC2
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./mathapp ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/mathapp

          # Run the binary in background
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${EC2_USER}@${EC2_HOST} "chmod +x /home/${EC2_USER}/mathapp && nohup /home/${EC2_USER}/mathapp > /home/${EC2_USER}/mathapp.log 2>&1 &"
