name: CI - build and test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run tests
        run: go test ./...

      - name: Build binary
        run: GOOS=linux GOARCH=amd64 go build -o mathapp .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: mathapp-binary
          path: mathapp

